#!/usr/bin/env bash
#USED THIS FOR NPR DATASET. DOESN'T COMBINE DATA
set -eou pipefail

nj=16
stage=0
stop_stage=9

# Split data/${lang}set to this number of pieces
# This is to avoid OOM during feature extraction.
num_splits=1000

# In case you want to use all validated data
use_validated=false

# In case you are willing to take the risk and use invalidated data
use_invalidated=false

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/$release/$lang
#      This directory contains the following files downloaded from
#       https://mozilla-common-voice-datasets.s3.dualstack.us-west-2.amazonaws.com/${release}/${release}-${lang}.tar.gz
#
#     - clips
#     - dev.tsv
#     - invalidated.tsv
#     - other.tsv
#     - reported.tsv
#     - test.tsv
#     - train.tsv
#     - validated.tsv
#
#  - $dl_dir/musan
#      This directory contains the following directories downloaded from
#       http://www.openslr.org/17/
#
#     - music
#     - noise
#     - speech

dl_dir=$PWD/download
data_dir=/../../../datasets/annaspeech_cuts_128GB
dataset="annaspeech"

#data_dir=$PWD/mnt/speech3/AnnaSpeech_opus_segments_v12/annaspeech_train_v12_6719325_segments
#release=cv-corpus-12.0-2022-12-07
#lang=fr
perturb_speed=false

. shared/parse_options.sh || exit 1

# vocab size for sentence piece models.
# It will generate data/${lang}/lang_bpe_xxx,
# data/${lang}/lang_bpe_yyy if the array contains xxx, yyy
# np: script recommended 2086
vocab_sizes=(
  # 5000
  # 2000
  # 1000
  500
  #1000
)

# All files generated by this script are saved in "data/${lang}".
# You can safely remove "data/${lang}" and rerun this script to regenerate it.
#mkdir -p data/${lang}

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if ! command -v ffmpeg &> /dev/null; then
  echo "This dataset requires ffmpeg"
  echo "Please install ffmpeg first"
  echo ""
  echo "  sudo apt-get install ffmpeg"
  exit 1
fi


log "Running prepare.sh"

log "dl_dir: $dl_dir"

if [ $stage -le -1 ] && [ $stop_stage -ge -1 ]; then
  log "Stage -1: Download LM"
  mkdir -p $dl_dir/lm
  if [ ! -e $dl_dir/lm/.done ]; then
    ./local/download_lm.py --out-dir=$dl_dir/lm
    touch $dl_dir/lm/.done
  fi
fi



if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download data"
#
#  # If you have pre-downloaded it to /path/to/$release,
#  # you can create a symlink
#  #
#  #   ln -sfv /path/to/$release $dl_dir/$release
#  #
#  if [ ! -d $dl_dir/$release/$lang/clips ]; then
#    lhotse download commonvoice --languages $lang --release $release $dl_dir
#  fi

  # If you have pre-downloaded it to /path/to/musan,
  # you can create a symlink
  #
  #   ln -sfv /path/to/musan $dl_dir/
  #
  if [ ! -d $dl_dir/musan ]; then
    lhotse download musan $dl_dir
  fi
fi

#dataset="npr_v8"

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare AnnaSpeech manifest"
  # We assume that you have downloaded the CommonVoice corpus
  # to $dl_dir/$release
  mkdir -p data/manifests
  if [ ! -e data/manifests/.as.done ]; then
    lhotse prepare annaspeech  --dataset $dataset -j $nj $data_dir data/manifests
    
    #if [ $use_validated = true ] && [ ! -f data/manifests/.as.validated.done ]; then
    #  log "Also prepare validated data"
    #  lhotse prepare annaspeech \
    #    --split validated \
    #    -j $nj $data_dir data/manifests
    #  touch data/manifests/.as.validated.done
    #fi

    #if [ $use_invalidated = true ] && [ ! -f data/manifests/.as.invalidated.done ]; then
    #  log "Also prepare invalidated data"
    #  lhotse prepare annaspeech \
    #    --split invalidated \
    #    -j $nj $data_dir data/manifests
    #  touch data/manifests/.as.invalidated.done
    #fi
    
    #touch data/manifests/.as.done
  fi

  # Note: in Linux, you can install jq with the following command:
  # 1. wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
  # 2. chmod +x ./jq
  # 3. cp jq /usr/bin
  #if [ $use_validated = true ]; then
  #  log "Getting cut ids from dev/test sets for later use"
  #  gunzip -c data/manifests/as-train_supervisions_test.jsonl.gz \
  #    | jq '.id' | sed 's/"//g' > data/manifests/as_test_ids
  #  
  #  gunzip -c data/${lang}/manifests/as_supervisions_dev.jsonl.gz \
  #    | jq '.id' | sed 's/"//g' > data/manifests/as_dev_ids
  #fi
fi



if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Prepare musan manifest"
  # We assume that you have downloaded the musan corpus
  # to data/musan
  mkdir -p data/manifests
  if [ ! -e data/manifests/.musan.done ]; then
    lhotse prepare musan $dl_dir/musan data/manifests
    touch data/manifests/.musan.done
  fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Compute fbank for musan"
  mkdir -p data/fbank
  if [ ! -e data/fbank/.musan.done ]; then
    ./local/compute_fbank_musan.py
    touch data/fbank/.musan.done
  fi
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  log "Stage 4: Compute fbank for librispeech"
  mkdir -p data/fbank
  if [ ! -e data/fbank/.annaspeech.done ]; then
    ./local/compute_fbank_annaspeech.py --dataset_name $dataset

    touch data/fbank/.annaspeech.done
  fi

#  if [ ! -f data/fbank/as_cuts_train-shuf.jsonl.gz ]; then
#    cat <(gunzip -c data/fbank/as_cuts_train.jsonl.gz) | shuf | gzip -c > data/fbank/as_cuts_train-shuf.jsonl.gz
#  fi

  if [ ! -e data/fbank/.annaspeech-validated.done ]; then
    log "Validating data/fbank for LibriSpeech"
#      train

    parts=(
      test
      dev
    )
    for part in ${parts[@]}; do
      python3 ./local/validate_manifest.py \
        data/fbank/${dataset}_cuts_${part}.jsonl.gz
    done
    touch data/fbank/.annaspeechspeech-validated.done
  fi
fi


num_per_split=1000
manifests_dir=data/manifests
if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
  log "Stage 4: Split medium and large subsets."
  for subset in small medium large; do
    log "Spliting subset : $subset"
    split_dir=$manifests_dir/${dataset}_${subset}_split
    mkdir -p $split_dir
    if [ ! -e $split_dir/.split_completed ]; then
      #lhotse split-lazy $manifests_dir/libriheavy_cuts_${subset}.jsonl.gz $split_dir $num_per_split
      #annaspeech_supervisions_train.jsonl.gz
      lhotse split $num_per_split $manifests_dir/${dataset}_supervisions_train.jsonl.gz $split_dir
      touch $split_dir/.split_completed
    fi
  done
fi

if [ $stage -le 6 ] && [ $stop_stage -ge 6 ]; then
  log "Stage 5: Split medium and large subsets."
  for subset in small medium large; do
    log "Spliting subset : $subset"
    split_dir=$manifests_dir/${dataset}_${subset}_split
    mkdir -p $split_dir
    if [ ! -e $split_dir/.recordings_split_completed ]; then
      #lhotse split-lazy $manifests_dir/libriheavy_cuts_${subset}.jsonl.gz $split_dir $num_per_split
      #annaspeech_supervisions_train.jsonl.gz
      lhotse split $num_per_split $manifests_dir/${dataset}_recordings_train.jsonl.gz $split_dir
      touch $split_dir/.recordings_split_completed
    fi
  done
fi

# this step takes 2 days
if [ $stage -le 7 ] && [ $stop_stage -ge 7 ]; then
  log "Stage 7: Compute features for train subset of CommonVoice"
  for subset in small medium large; do
      perturb_speed=false
      echo ${dataset}"_supervisions_train.*.jsonl.gz"
      num_splits=$(find $manifests_dir/${dataset}_${subset}_split -name ${dataset}"_supervisions_train.*.jsonl.gz" | wc -l)
      echo $num_splits
      #why are we doing this??? 
      cp -r data/manifests/${dataset}_train_split data/fbank
      #dataset_parts=("train")
      if [ ! -e data/fbank/.annaspeech_train.done ]; then
          for split_number in $(seq -f "%04g" 1 $num_splits);
          do
              echo "split_number: "
              echo $split_number
              ./local/compute_fbank_annaspeech_splits.py --dataset_name $dataset \
               --perturb-speed $perturb_speed \
               --split-number $split_number
          done

        #./local/compute_fbank_annaspeech_splits.py \
        #  --perturb-speed $perturb_speed

        #touch data/fbank/.annaspeech_train.done
      fi
  done
fi


if [ $stage -le 8 ] && [ $stop_stage -ge 8 ]; then
  log "Stage 8: Combine features for medium and large subsets."
  fbank_dir=data/fbank
  for subset in small medium large; do
    log "Combining $subset subset."
    echo ${dataset}
    if [ ! -f $fbank_dir/${dataset}_cuts_${subset}.jsonl.gz ]; then
      #pieces=$(find $fbank_dir/${dataset}_${subset}_split -name ${dataset}"_cuts_train.*.jsonl.gz")
      pieces=$(find $fbank_dir/${dataset}_train_split -name ${dataset}"_cuts_train.*.jsonl.gz")

      echo $pieces
      echo $pieces $fbank_dir/${dataset}_cuts_${subset}.jsonl.gz

      lhotse combine $pieces $fbank_dir/${dataset}_cuts_${subset}.jsonl.gz
    fi
    if [ ! -f data/fbank/${dataset}_cuts_train-shuf.jsonl.gz ]; then
        cat <(gunzip -c data/fbank/${dataset}_cuts_train.jsonl.gz) | shuf | gzip -c > data/fbank/${dataset}_cuts_train-shuf.jsonl.gz
    fi
  done
fi



if [ $stage -le 9 ] && [ $stop_stage -ge 9 ]; then
  log "Stage 9: Prepare BPE based lang"

  for vocab_size in ${vocab_sizes[@]}; do
    lang_dir=data/lang_bpe_${vocab_size}
    mkdir -p $lang_dir

    if [ ! -f $lang_dir/transcript_words.txt ]; then
      log "Generate data for BPE training"
      #cat $data_dir/all_train_v8.txt > $lang_dir/transcript_words.txt
      cat $data_dir/large/metadata_cleaned.tsv | cut -f4 | sed '1d'  > $lang_dir/transcript_words.txt
      echo $vocab_size
      echo $lang_dir
    fi
    if [ ! -f $lang_dir/bpe.model ]; then
      ./local/train_bpe_model.py \
        --lang-dir $lang_dir \
        --vocab-size $vocab_size \
        --transcript $lang_dir/transcript_words.txt \
        --character-coverage 0.99999
    fi
  done
fi

exit 0



















